import type { Booking } from './types'

export const mockBookings: Booking[] = [
  {
    id: 'bk_001',
    clientId: 'client_001',
    serviceType: 'Limpieza regular',
    date: '2026-05-14',
    startTime: '10:00',
    duration: 3,
    frequency: 'once',
    status: 'pending',
    address: 'Pocitos, Montevideo',
    extras: ['Heladera'],
    price: 1500,
  },
  {
    id: 'bk_002',
    clientId: 'client_002',
    workerId: 'worker_001',
    serviceType: 'Limpieza profunda',
    date: '2026-05-15',
    startTime: '09:00',
    duration: 4,
    frequency: 'weekly',
    status: 'accepted',
    address: 'Centro, Montevideo',
    extras: ['Horno', 'Ventanas'],
    price: 2500,
  },
  {
    id: 'bk_003',
    clientId: 'client_003',
    workerId: 'worker_002',
    serviceType: 'Home organization',
    date: '2026-05-08',
    startTime: '14:00',
    duration: 2,
    frequency: 'biweekly',
    status: 'completed',
    address: 'Carrasco, Montevideo',
    extras: ['Placares'],
    price: 2000,
  },
]
